# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Charles\Documents\GitHub\Blocky-Chess-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Charles\Documents\GitHub\Blocky-Chess-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Charles\Documents\GitHub\Blocky-Chess-Engine\CMakeFiles C:\Users\Charles\Documents\GitHub\Blocky-Chess-Engine\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Charles\Documents\GitHub\Blocky-Chess-Engine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Blocky

# Build rule for target.
Blocky: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Blocky
.PHONY : Blocky

# fast build rule for target.
Blocky/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/build
.PHONY : Blocky/fast

src/bitboard.obj: src/bitboard.cpp.obj
.PHONY : src/bitboard.obj

# target to build an object file
src/bitboard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/bitboard.cpp.obj
.PHONY : src/bitboard.cpp.obj

src/bitboard.i: src/bitboard.cpp.i
.PHONY : src/bitboard.i

# target to preprocess a source file
src/bitboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/bitboard.cpp.i
.PHONY : src/bitboard.cpp.i

src/bitboard.s: src/bitboard.cpp.s
.PHONY : src/bitboard.s

# target to generate assembly for a file
src/bitboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/bitboard.cpp.s
.PHONY : src/bitboard.cpp.s

src/board.obj: src/board.cpp.obj
.PHONY : src/board.obj

# target to build an object file
src/board.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/board.cpp.obj
.PHONY : src/board.cpp.obj

src/board.i: src/board.cpp.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/eval.obj: src/eval.cpp.obj
.PHONY : src/eval.obj

# target to build an object file
src/eval.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/eval.cpp.obj
.PHONY : src/eval.cpp.obj

src/eval.i: src/eval.cpp.i
.PHONY : src/eval.i

# target to preprocess a source file
src/eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/eval.cpp.i
.PHONY : src/eval.cpp.i

src/eval.s: src/eval.cpp.s
.PHONY : src/eval.s

# target to generate assembly for a file
src/eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/eval.cpp.s
.PHONY : src/eval.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/move.obj: src/move.cpp.obj
.PHONY : src/move.obj

# target to build an object file
src/move.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/move.cpp.obj
.PHONY : src/move.cpp.obj

src/move.i: src/move.cpp.i
.PHONY : src/move.i

# target to preprocess a source file
src/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/move.cpp.i
.PHONY : src/move.cpp.i

src/move.s: src/move.cpp.s
.PHONY : src/move.s

# target to generate assembly for a file
src/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/move.cpp.s
.PHONY : src/move.cpp.s

src/moveGen.obj: src/moveGen.cpp.obj
.PHONY : src/moveGen.obj

# target to build an object file
src/moveGen.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/moveGen.cpp.obj
.PHONY : src/moveGen.cpp.obj

src/moveGen.i: src/moveGen.cpp.i
.PHONY : src/moveGen.i

# target to preprocess a source file
src/moveGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/moveGen.cpp.i
.PHONY : src/moveGen.cpp.i

src/moveGen.s: src/moveGen.cpp.s
.PHONY : src/moveGen.s

# target to generate assembly for a file
src/moveGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/moveGen.cpp.s
.PHONY : src/moveGen.cpp.s

src/search.obj: src/search.cpp.obj
.PHONY : src/search.obj

# target to build an object file
src/search.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/search.cpp.obj
.PHONY : src/search.cpp.obj

src/search.i: src/search.cpp.i
.PHONY : src/search.i

# target to preprocess a source file
src/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/search.cpp.i
.PHONY : src/search.cpp.i

src/search.s: src/search.cpp.s
.PHONY : src/search.s

# target to generate assembly for a file
src/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/search.cpp.s
.PHONY : src/search.cpp.s

src/timeman.obj: src/timeman.cpp.obj
.PHONY : src/timeman.obj

# target to build an object file
src/timeman.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/timeman.cpp.obj
.PHONY : src/timeman.cpp.obj

src/timeman.i: src/timeman.cpp.i
.PHONY : src/timeman.i

# target to preprocess a source file
src/timeman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/timeman.cpp.i
.PHONY : src/timeman.cpp.i

src/timeman.s: src/timeman.cpp.s
.PHONY : src/timeman.s

# target to generate assembly for a file
src/timeman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/timeman.cpp.s
.PHONY : src/timeman.cpp.s

src/uci.obj: src/uci.cpp.obj
.PHONY : src/uci.obj

# target to build an object file
src/uci.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/uci.cpp.obj
.PHONY : src/uci.cpp.obj

src/uci.i: src/uci.cpp.i
.PHONY : src/uci.i

# target to preprocess a source file
src/uci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/uci.cpp.i
.PHONY : src/uci.cpp.i

src/uci.s: src/uci.cpp.s
.PHONY : src/uci.s

# target to generate assembly for a file
src/uci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blocky.dir\build.make CMakeFiles/Blocky.dir/src/uci.cpp.s
.PHONY : src/uci.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Blocky
	@echo ... src/bitboard.obj
	@echo ... src/bitboard.i
	@echo ... src/bitboard.s
	@echo ... src/board.obj
	@echo ... src/board.i
	@echo ... src/board.s
	@echo ... src/eval.obj
	@echo ... src/eval.i
	@echo ... src/eval.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/move.obj
	@echo ... src/move.i
	@echo ... src/move.s
	@echo ... src/moveGen.obj
	@echo ... src/moveGen.i
	@echo ... src/moveGen.s
	@echo ... src/search.obj
	@echo ... src/search.i
	@echo ... src/search.s
	@echo ... src/timeman.obj
	@echo ... src/timeman.i
	@echo ... src/timeman.s
	@echo ... src/uci.obj
	@echo ... src/uci.i
	@echo ... src/uci.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

